---
- name: Install GitLab dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - perl
      - openssh-server
      - tzdata
      - python3-selinux
      - selinux-utils     # Required to manage/ignore SELinux types
    state: present
    update_cache: true
  become: true

- name: Create GitLab configuration directory
  ansible.builtin.file:
    path: /etc/gitlab
    state: directory
    owner: root
    group: root
    mode: '0775'
  become: true

- name: Pre-place GitLab configuration
  # We place this BEFORE install so the package knows to ignore SELinux immediately
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0600'
  become: true
  register: gitlab_config

- name: Setup GitLab Repository
  block:
    - name: Download installation script
      ansible.builtin.get_url:
        url: "{{ gitlab_repo_script_url }}"
        dest: /tmp/gitlab_repo.sh
        mode: '0700'
    
    - name: Run installation script
      ansible.builtin.command: bash /tmp/gitlab_repo.sh
      args:
        creates: "/etc/apt/sources.list.d/gitlab_gitlab-{{ gitlab_edition_short }}.list"
  become: true

- name: Install GitLab {{ gitlab_edition }}
  ansible.builtin.apt:
    name: "{{ gitlab_edition }}"
    state: present
  become: true
  environment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"
    # IMPORTANT: Prevents automatic reconfigure during apt install 
    # which usually fails on the first run with SELinux enabled.
    SKIP_POST_INSTALL_RECONFIGURE: "true"

- name: Run GitLab reconfigure
  # Run only if the template changed or if this is the initial install
  ansible.builtin.command: gitlab-ctl reconfigure
  become: true
  when: gitlab_config.changed or (ansible_check_mode | bool == false)

- name: Cleanup temporary installation script
  ansible.builtin.file:
    path: /tmp/gitlab_repo.sh
    state: absent
  become: true