---
gitlab_edition: "gitlab-ee"
gitlab_edition_short: "ee" # used for repo list filename
gitlab_repo_script_url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh"
gitlab_external_url: "http://gitlab.example.com"
# Set to false to bypass the internal Chef SELinux labeling tasks
gitlab_selinux_enabled: false